source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Dropper_Example', :exclusive => true do
  pod "Dropper", :path => "../"
end

target 'Dropper_Tests', :exclusive => true do
  pod "Dropper", :path => "../"

  
end
