source 'https://github.com/CocoaPods/Specs.git'
inhibit_all_warnings!
xcodeproj 'Dropper'
use_frameworks!



target 'Dropper_Example' do
  pod "Dropper", :path => "../"
  
  post_install do |installer|
      installer.pods_project.targets.each do |target|
          target.build_configurations.each do |config|
              config.build_settings['SWIFT_VERSION'] = '3.0'
          end
      end
  end
end

target 'Dropper_Tests' do
  pod "Dropper", :path => "../"
end
